### ISSUE TITLE
Not updating custom URL categories

### ISSUE THREAD

**Issue by f5regan** [f5devcentral/sslo-o365-update#1]
This script is failing to update custom URL categories due to a misconfiguration in where the categories are created vs. where the script looks to see if they already exist.

When the script initially creates the category, it does not specify a path, just an object name, so the category is created in /Common
https://github.com/f5devcentral/sslo-o365-update/blob/c2cf6d6338f74813b05caff0d659c81d5acc977e/sslo_o365_update.py#L582

When the script needs to update the category, it looks for the category in /Common/o365_update.app/ 
https://github.com/f5devcentral/sslo-o365-update/blob/c2cf6d6338f74813b05caff0d659c81d5acc977e/sslo_o365_update.py#L580

This results in this piece of code executing every time, regardless of whether the category already exists or not, which results in a TMSH error and a failure to update the category:
https://github.com/f5devcentral/sslo-o365-update/blob/c2cf6d6338f74813b05caff0d659c81d5acc977e/sslo_o365_update.py#L581-L583

I tested creating a URL category in the application service folder (ex. create sys url-db url-category /Common/o365_update.app/Office_365_Managed_All) and in SSL Orchestrator 9.1 it seems to work in the limited testing I've conducted (created rule referencing category and confirmed the rule matched for a domain in the category when sending a request through). The other option would be to remove "o365_update.app/" from Line 580 but this results in some objects (URL categories) sitting in /Common and others (data groups) sitting in /Common/o365_update.app.

**Comment by kevingstewart** [comment]
Fixes implemented in 7.2.6.
